/**
 * journey/pdf-export.js
 * ─────────────────────────────────────────────────────────────
 * Generates a downloadable PDF report (weekly or monthly) using
 * jsPDF (loaded via CDN in tracker.html). Builds the PDF directly
 * from structured data — no HTML-to-canvas conversion needed,
 * which keeps output crisp and file size small.
 * ─────────────────────────────────────────────────────────────
 */

const DFPdfExport = (function () {

  function addHeader(doc, title, subtitle) {
    doc.setFillColor(26, 39, 68); // navy
    doc.rect(0, 0, 210, 32, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('DaibFit Journey', 14, 16);
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text(title, 14, 24);
    doc.setFontSize(9);
    doc.setTextColor(200, 200, 200);
    doc.text(subtitle, 14, 29);
    doc.setTextColor(0, 0, 0);
  }

  function addFooter(doc) {
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by DaibFit Journey · daibfit.in · General wellness guidance, not medical advice', 14, 287);
  }

  function statRow(doc, y, label, value) {
    doc.setFontSize(10);
    doc.setTextColor(90, 90, 90);
    doc.text(label, 14, y);
    doc.setFontSize(12);
    doc.setTextColor(20, 20, 20);
    doc.setFont(undefined, 'bold');
    doc.text(String(value), 140, y);
    doc.setFont(undefined, 'normal');
  }

  /**
   * Generates and triggers download of a weekly report PDF.
   * @param {Object} data - { userName, weekLabel, consistencyScore, totalWalkMinutes, totalKm, avgSleep, insights }
   */
  function exportWeeklyReport(data) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    addHeader(doc, 'Weekly Progress Report', data.weekLabel);

    doc.setFontSize(13);
    doc.setTextColor(20, 20, 20);
    doc.text(`Hi ${data.userName || 'there'}, here's your week in review.`, 14, 46);

    let y = 62;
    doc.setDrawColor(230, 230, 230);
    doc.line(14, y - 8, 196, y - 8);

    statRow(doc, y, 'Consistency score', `${data.consistencyScore}/100`); y += 12;
    statRow(doc, y, 'Total activity time', `${data.totalWalkMinutes} min`); y += 12;
    statRow(doc, y, 'Estimated distance', `${data.totalKm} km`); y += 12;
    statRow(doc, y, 'Average sleep', `${data.avgSleep || '—'} hrs/night`); y += 20;

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Your insights this week', 14, y); y += 8;
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    (data.insights || []).forEach(insight => {
      const lines = doc.splitTextToSize(`• ${insight.text}`, 180);
      doc.text(lines, 14, y);
      y += lines.length * 6 + 2;
    });

    addFooter(doc);
    doc.save(`DaibFit-Weekly-Report-${data.weekLabel.replace(/\s/g, '-')}.pdf`);
  }

  /**
   * Generates and triggers download of a monthly report PDF.
   * @param {Object} data - { userName, monthLabel, consistencyScore, totalKm, weightChange, insights, bodyAge, riskLevel }
   */
  function exportMonthlyReport(data) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    addHeader(doc, 'Monthly Progress Report', data.monthLabel);

    doc.setFontSize(13);
    doc.setTextColor(20, 20, 20);
    doc.text(`Hi ${data.userName || 'there'}, here's your month in review.`, 14, 46);

    let y = 62;
    statRow(doc, y, 'Consistency score', `${data.consistencyScore}/100`); y += 12;
    statRow(doc, y, 'Distance covered', `${data.totalKm} km`); y += 12;
    statRow(doc, y, 'Weight change', data.weightChange !== undefined ? `${data.weightChange} kg` : '—'); y += 12;
    if (data.bodyAge) { statRow(doc, y, 'Latest Body Age', `${data.bodyAge} yrs`); y += 12; }
    if (data.riskLevel) { statRow(doc, y, 'Latest risk level', data.riskLevel); y += 12; }
    y += 8;

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Recommendations', 14, y); y += 8;
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    (data.insights || []).forEach(insight => {
      const lines = doc.splitTextToSize(`• ${insight.text}`, 180);
      doc.text(lines, 14, y);
      y += lines.length * 6 + 2;
    });

    addFooter(doc);
    doc.save(`DaibFit-Monthly-Report-${data.monthLabel.replace(/\s/g, '-')}.pdf`);
  }

  return { exportWeeklyReport, exportMonthlyReport };
})();
